In [60]:
import pandas_datareader.data as pdr
from datetime import datetime, timedelta
from my_trader import *

In [39]:
start=datetime.now()-timedelta(days =256)
end = datetime.now()

# Historical Data

## 1. Quandl

In [46]:
pdr.DataReader("AAPL","quandl",start,end)

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2018-03-27,173.680,175.1500,166.9200,168.340,38962839.0,0.0,1.0,173.680,175.1500,166.9200,168.340,38962839.0
2018-03-26,168.070,173.1000,166.4400,172.770,36272617.0,0.0,1.0,168.070,173.1000,166.4400,172.770,36272617.0
2018-03-23,168.390,169.9200,164.9400,164.940,40248954.0,0.0,1.0,168.390,169.9200,164.9400,164.940,40248954.0
2018-03-22,170.000,172.6800,168.6000,168.845,41051076.0,0.0,1.0,170.000,172.6800,168.6000,168.845,41051076.0
2018-03-21,175.040,175.0900,171.2600,171.270,35247358.0,0.0,1.0,175.040,175.0900,171.2600,171.270,35247358.0
2018-03-20,175.240,176.8000,174.9400,175.240,19314039.0,0.0,1.0,175.240,176.8000,174.9400,175.240,19314039.0
2018-03-19,177.320,177.4700,173.6600,175.300,32804695.0,0.0,1.0,177.320,177.4700,173.6600,175.300,32804695.0
2018-03-16,178.650,179.1200,177.6200,178.020,36836456.0,0.0,1.0,178.650,179.1200,177.6200,178.020,36836456.0
2018-03-15,178.500,180.2400,178.0701,178.650,22584565.0,0.0,1.0,178.500,180.2400,178.0701,178.650,22584565.0
2018-03-14,180.320,180.5200,177.8100,178.440,29075469.0,0.0,1.0,180.320,180.5200,177.8100,178.440,29075469.0
2018-03-13,182.590,183.5000,179.2400,179.970,31168404.0,0.0,1.0,182.590,183.5000,179.2400,179.970,31168404.0
2018-03-12,180.290,182.3900,180.2100,181.720,32055405.0,0.0,1.0,180.290,182.3900,180.2100,181.720,32055405.0
2018-03-09,177.960,180.0000,177.3900,179.980,31385134.0,0.0,1.0,177.960,180.0000,177.3900,179.980,31385134.0
2018-03-08,175.480,177.1200,175.0700,176.940,23163767.0,0.0,1.0,175.480,177.1200,175.0700,176.940,23163767.0
2018-03-07,174.940,175.8500,174.2700,175.030,31703462.0,0.0,1.0,174.940,175.8500,174.2700,175.030,31703462.0
2018-03-06,177.910,178.2500,176.1300,176.670,23788506.0,0.0,1.0,177.910,178.2500,176.1300,176.670,23788506.0
2018-03-05,175.210,177.7400,174.5200,176.820,28401366.0,0.0,1.0,175.210,177.7400,174.5200,176.820,28401366.0
2018-03-02,172.800,176.3000,172.4500,176.210,38453950.0,0.0,1.0,172.800,176.3000,172.4500,176.210,38453950.0
2018-03-01,178.540,179.7750,172.6600,175.000,48801970.0,0.0,1.0,178.540,179.7750,172.6600,175.000,48801970.0
2018-02-28,179.260,180.6150,178.0500,178.120,33604574.0,0.0,1.0,179.260,180.6150,178.0500,178.120,33604574.0
2018-02-27,179.100,180.4800,178.1600,178.390,38685165.0,0.0,1.0,179.100,180.4800,178.1600,178.390,38685165.0
2018-02-26,176.350,179.3900,176.2100,178.970,36886432.0,0.0,1.0,176.350,179.3900,176.2100,178.970,36886432.0
2018-02-23,173.670,175.6500,173.5400,175.555,33329232.0,0.0,1.0,173.670,175.6500,173.5400,175.555,33329232.0
2018-02-22,171.800,173.9500,171.7100,172.600,30504116.0,0.0,1.0,171.800,173.9500,171.7100,172.600,30504116.0
2018-02-21,172.830,174.1200,171.0100,171.070,35833514.0,0.0,1.0,172.830,174.1200,171.0100,171.070,35833514.0
2018-02-20,172.050,174.2600,171.4200,171.850,33531012.0,0.0,1.0,172.050,174.2600,171.4200,171.850,33531012.0
2018-02-16,172.360,174.8200,171.7700,172.430,39638793.0,0.0,1.0,172.360,174.8200,171.7700,172.430,39638793.0
2018-02-15,169.790,173.0900,169.0000,172.990,50609595.0,0.0,1.0,169.790,173.0900,169.0000,172.990,50609595.0
2018-02-14,163.045,167.5400,162.8800,167.370,39669178.0,0.0,1.0,163.045,167.5400,162.8800,167.370,39669178.0
2018-02-13,161.950,164.7500,161.6500,164.340,32104756.0,0.0,1.0,161.950,164.7500,161.6500,164.340,32104756.0
2018-02-12,158.500,163.8900,157.5100,162.710,60560145.0,0.0,1.0,158.500,163.8900,157.5100,162.710,60560145.0
2018-02-09,157.070,157.8900,150.2400,155.970,66723743.0,0.0,1.0,157.070,157.8900,150.2400,155.970,66723743.0
2018-02-08,160.290,161.0000,155.0300,155.320,49594129.0,0.0,1.0,160.290,161.0000,155.0300,155.320,49594129.0
2018-02-07,163.085,163.4000,159.0685,159.540,50852130.0,0.0,1.0,163.085,163.4000,159.0685,159.540,50852130.0
2018-02-06,154.830,163.7200,154.0000,163.030,66625484.0,0.0,1.0,154.830,163.7200,154.0000,163.030,66625484.0
2018-02-05,159.100,163.8800,156.0000,157.490,66090446.0,0.0,1.0,159.100,163.8800,156.0000,157.490,66090446.0
2018-02-02,166.000,166.8000,160.1000,160.370,85436075.0,0.0,1.0,166.000,166.8000,160.1000,160.370,85436075.0
2018-02-01,167.165,168.6200,166.7600,167.780,38099665.0,0.0,1.0,167.165,168.6200,166.7600,167.780,38099665.0
2018-01-31,166.870,168.4417,166.5000,167.430,30984099.0,0.0,1.0,166.870,168.4417,166.5000,167.430,30984099.0
2018-01-30,165.525,167.3700,164.7000,166.970,45137026.0,0.0,1.0,165.525,167.3700,164.7000,166.970,45137026.0
2018-01-29,170.160,170.1600,167.0700,167.960,48434424.0,0.0,1.0,170.160,170.1600,167.0700,167.960,48434424.0
2018-01-26,172.000,172.0000,170.0600,171.510,37121805.0,0.0,1.0,172.000,172.0000,170.0600,171.510,37121805.0
2018-01-25,174.505,174.9500,170.5300,171.110,39661804.0,0.0,1.0,174.505,174.9500,170.5300,171.110,39661804.0
2018-01-24,177.250,177.3000,173.2000,174.220,50562257.0,0.0,1.0,177.250,177.3000,173.2000,174.220,50562257.0
2018-01-23,177.300,179.4400,176.8200,177.040,31702531.0,0.0,1.0,177.300,179.4400,176.8200,177.040,31702531.0
2018-01-22,177.300,177.7800,176.6016,177.000,26023683.0,0.0,1.0,177.300,177.7800,176.6016,177.000,26023683.0
2018-01-19,178.610,179.5800,177.4100,178.460,30827809.0,0.0,1.0,178.610,179.5800,177.4100,178.460,30827809.0
2018-01-18,179.370,180.1000,178.2500,179.260,30234512.0,0.0,1.0,179.370,180.1000,178.2500,179.260,30234512.0
2018-01-17,176.150,179.2500,175.0700,179.100,32752734.0,0.0,1.0,176.150,179.2500,175.0700,179.100,32752734.0
2018-01-16,177.900,179.3900,176.1400,176.190,29159005.0,0.0,1.0,177.900,179.3900,176.1400,176.190,29159005.0
2018-01-12,176.180,177.3600,175.6500,177.090,25039531.0,0.0,1.0,176.180,177.3600,175.6500,177.090,25039531.0
2018-01-11,174.590,175.4886,174.4900,175.280,17523256.0,0.0,1.0,174.590,175.4886,174.4900,175.280,17523256.0
2018-01-10,173.160,174.3000,173.0000,174.290,23589129.0,0.0,1.0,173.160,174.3000,173.0000,174.290,23589129.0
2018-01-09,174.550,175.0600,173.4100,174.330,21262614.0,0.0,1.0,174.550,175.0600,173.4100,174.330,21262614.0
2018-01-08,174.350,175.6100,173.9300,174.350,20134092.0,0.0,1.0,174.350,175.6100,173.9300,174.350,20134092.0

## 2. ALPHA VANTAGE

In [83]:
api = "R9KJYWUBMIDAXNW7"
function ="TIME_SERIES_DAILY_ADJUSTED"
data_size = "compact"

In [84]:
ticker = "AAPL"

In [85]:
api_url = 'https://www.alphavantage.co/query?' + 'function={}&symbol={}&apikey={}&outputsize={}&datatype=csv'\
                                     .format(function, ticker, api,data_size)

In this case, the API returns CSV file

In [88]:
pd.read_csv(api_url)

,timestamp,open,high,low,close,adjusted_close,volume,dividend_amount,split_coefficient
0,2018-09-20,220.2400,222.2800,219.1500,220.03,220.0300,26380446,0.00,1.0
1,2018-09-19,218.5000,219.6200,215.3000,218.37,218.3700,27123833,0.00,1.0
2,2018-09-18,217.7900,221.8500,217.1200,218.24,218.2400,31571712,0.00,1.0
3,2018-09-17,222.1500,222.9500,217.2700,217.88,217.8800,37195133,0.00,1.0
4,2018-09-14,225.7500,226.8400,222.5220,223.84,223.8400,31999289,0.00,1.0
5,2018-09-13,223.5200,228.3500,222.5700,226.41,226.4100,41706377,0.00,1.0
6,2018-09-12,224.9400,225.0000,219.8400,221.07,221.0700,49278740,0.00,1.0
7,2018-09-11,218.0100,224.2990,216.5600,223.85,223.8500,35749049,0.00,1.0
8,2018-09-10,220.9500,221.8500,216.4700,218.33,218.3300,39516453,0.00,1.0
9,2018-09-07,221.8500,225.3700,220.7100,221.30,221.3000,37619810,0.00,1.0
10,2018-09-06,226.2300,227.3500,221.3000,223.10,223.1000,34289976,0.00,1.0
11,2018-09-05,228.9900,229.6700,225.1000,226.87,226.8700,33332960,0.00,1.0
12,2018-09-04,228.4100,229.1800,226.6300,228.36,228.3600,27390132,0.00,1.0
13,2018-08-31,226.5100,228.8700,226.0000,227.63,227.6300,43340134,0.00,1.0
14,2018-08-30,223.2500,228.2600,222.4000,225.03,225.0300,48793824,0.00,1.0
15,2018-08-29,220.1500,223.4900,219.4100,222.98,222.9800,27254804,0.00,1.0
16,2018-08-28,219.0100,220.5400,218.9200,219.70,219.7000,22776766,0.00,1.0
17,2018-08-27,217.1500,218.7400,216.3300,217.94,217.9400,20525117,0.00,1.0
18,2018-08-24,216.6000,216.9000,215.1100,216.16,216.1600,18476356,0.00,1.0
19,2018-08-23,214.6500,217.0500,214.6000,215.49,215.4900,18883224,0.00,1.0
20,2018-08-22,214.1000,216.3600,213.8400,215.05,215.0500,19018131,0.00,1.0
21,2018-08-21,216.8000,217.1900,214.0250,215.04,215.0400,26159755,0.00,1.0
22,2018-08-20,218.1000,219.1800,215.1100,215.46,215.4600,30287695,0.00,1.0
23,2018-08-17,213.4400,217.9500,213.1600,217.58,217.5800,35426997,0.00,1.0
24,2018-08-16,211.7500,213.8121,211.4700,213.32,213.3200,28500367,0.00,1.0
25,2018-08-15,209.2200,210.7400,208.3300,210.24,210.2400,28807564,0.00,1.0
26,2018-08-14,210.1550,210.5600,208.2600,209.75,209.7500,20748010,0.00,1.0
27,2018-08-13,207.7000,210.9520,207.7000,208.87,208.8700,25890880,0.00,1.0
28,2018-08-10,207.3600,209.1000,206.6700,207.53,207.5300,24611202,0.73,1.0
29,2018-08-09,207.2800,209.7800,207.2000,208.88,208.1478,23492626,0.00,1.0
...,...,...,...,...,...,...,...,...,...
70,2018-06-12,191.3850,192.6110,191.1500,192.28,191.6060,16911141,0.00,1.0
71,2018-06-11,191.3500,191.9700,190.2100,191.23,190.5597,18308460,0.00,1.0
72,2018-06-08,191.1700,192.0000,189.7700,191.70,191.0280,26656799,0.00,1.0
73,2018-06-07,194.1400,194.2000,192.3350,193.46,192.7819,21347180,0.00,1.0
74,2018-06-06,193.6300,194.0800,191.9200,193.98,193.3001,20933619,0.00,1.0
75,2018-06-05,193.0650,193.9400,192.3600,193.31,192.6324,21565963,0.00,1.0
76,2018-06-04,191.6350,193.4200,191.3500,191.83,191.1576,26266174,0.00,1.0
77,2018-06-01,187.9912,190.2600,187.7500,190.24,189.5732,23442510,0.00,1.0
78,2018-05-31,187.2200,188.2300,186.1400,186.87,186.2150,27482793,0.00,1.0
79,2018-05-30,187.7200,188.0000,186.7800,187.50,186.8428,18690547,0.00,1.0
80,2018-05-29,187.6000,188.7500,186.8700,187.90,187.2414,22514075,0.00,1.0
81,2018-05-25,188.2300,189.6500,187.6500,188.58,187.9190,17460963,0.00,1.0
82,2018-05-24,188.7700,188.8400,186.2100,188.15,187.4905,23233975,0.00,1.0
83,2018-05-23,186.3500,188.5000,185.7600,188.36,187.6998,20058415,0.00,1.0
84,2018-05-22,188.3750,188.8800,186.7800,187.16,186.5040,15240704,0.00,1.0
85,2018-05-21,188.0000,189.2700,186.9106,187.63,186.9723,18400787,0.00,1.0
86,2018-05-18,187.1900,187.8102,186.1300,186.31,185.6569,18297728,0.00,1.0
87,2018-05-17,188.0000,188.9100,186.3600,186.99,186.3346,17294029,0.00,1.0
88,2018-05-16,186.0700,188.4600,186.0000,188.18,187.5204,19183064,0.00,1.0
89,2018-05-15,186.7800,187.0700,185.1000,186.44,185.7865,23695159,0.00,1.0
90,2018-05-14,189.0100,189.5300,187.8600,188.15,187.4905,20778772,0.00,1.0
91,2018-05-11,189.4900,190.0600,187.4500,188.59,187.9289,26212221,0.73,1.0
92,2018-05-10,187.7400,190.3700,187.6500,190.04,188.6437,27989289,0.00,1.0
93,2018-05-09,186.5500,187.4000,185.2200,187.36,185.9833,23211241,0.00,1.0
94,2018-05-08,184.9900,186.2200,183.6650,186.05,184.6830,28402777,0.00,1.0
95,2018-05-07,185.1800,187.6700,184.7500,185.16,183.7995,42451423,0.00,1.0
96,2018-05-04,178.2500,184.2500,178.1700,183.83,182.4793,56201317,0.00,1.0
97,2018-05-03,175.8800,177.5000,174.4411,176.89,175.5903,34068180,0.00,1.0
98,2018-05-02,175.2250,177.7500,173.8000,176.57,175.2726,66539371,0.00,1.0
99,2018-05-01,166.4102,169.2000,165.2700,169.10,167.8575,53569376,0.00,1.0

The only drawback for Alpha Vantage is that you can not set a date range for the data

# Stock Quote

## https://financialmodelingprep.com/

In [90]:
ticker_1="AAPL"

In [91]:
quote_url="https://financialmodelingprep.com/api/company/price/{}".format(ticker_1)

In [96]:
import requests as re

In [98]:
re.

AttributeError: 'module' object has no attribute 'text'